// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqOYMystQ7Btx9CKyzdtkP7kRPH-IBbk',
    appId: '1:548420428191:web:f1876693bb292143241daa',
    messagingSenderId: '548420428191',
    projectId: 'authnutritionaldiabetesapp',
    authDomain: 'authnutritionaldiabetesapp.firebaseapp.com',
    storageBucket: 'authnutritionaldiabetesapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrsSonBelfsty8Piwlw6LqQSLj9EJnj8',
    appId: '1:548420428191:android:2a4f2f8eac26707b241daa',
    messagingSenderId: '548420428191',
    projectId: 'authnutritionaldiabetesapp',
    storageBucket: 'authnutritionaldiabetesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhvhEcPpSjNSCDQ_jjDObJgBUVf9fmYKc',
    appId: '1:548420428191:ios:6d5978afed6360e4241daa',
    messagingSenderId: '548420428191',
    projectId: 'authnutritionaldiabetesapp',
    storageBucket: 'authnutritionaldiabetesapp.appspot.com',
    iosBundleId: 'com.example.tesisProjectV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhvhEcPpSjNSCDQ_jjDObJgBUVf9fmYKc',
    appId: '1:548420428191:ios:35ddf896712a2dbe241daa',
    messagingSenderId: '548420428191',
    projectId: 'authnutritionaldiabetesapp',
    storageBucket: 'authnutritionaldiabetesapp.appspot.com',
    iosBundleId: 'com.example.tesisProjectV1.RunnerTests',
  );
}
